using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ParticleCollider : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    //public void OnParticleTrigger()
    //{

    //    Debug.Log("IT WORKS???");

    //}

    public void OnParticleCollision(GameObject other)
    {

        if(other.GetComponent<PermanentOutline>() != null)
        {

            if(other.GetComponent<Outline>().enabled == false)
            {

                other.GetComponent<PermanentOutline>().EnabledOutline();

            }
            if (other.GetComponent<Outline>().enabled == true)
            {

                other.GetComponent<PermanentOutline>().DisableOutline();

            }

        }


    }

}
